export * from  './Header/Header'
export * from './Movies/Movies'
export * from './Movie/Movie'
export * from './Pagination/Pagination'
export * from './Genres/Genres'
export * from './Details/Details'
